const routes = [
    { path: '/', exact: true },
    { path: '/index.html' },
    { path: '/home' },
    { path: '/about' },
    { path: '/product' },
    { path: '/product-search' },
    { path: '/disclaimer' },
    { path: '/privacy-policy' },
    { path: '/returns-exchanges' },
    { path: '/paid-consultation' },
    { path: '/delivery-information' },
    { path: '/terms-conditions' },
    { path: '/contact-us' },
    { path: '/career' },
    { path: '/faq-help' },
    { path: '/news' },
    { path: '/blogs' },
    { path: '/testimonial' },
    { path: '/chairman-s-message' },
    { path: '/download' },
    { path: '/cart' },
    { path: '/checkout' },
    { path: '/quality-certification' },
    { path: '/about-homoeopathic' },
    { path: '/care-plan' },
    { path: '/ailment-vs-remedy' },
    { path: '/dealer-locator' },
    { path: '/certificate-download' },
    { path: '/membership' },
    { path: '/membership/savings' },
    { path: '/login' },
    { path: '/register' },
    { path: '/forgot-password' },
    { path: '/reset-password' },
    { path: '/profile' },
    { path: '/update-profile' },
    { path: '/change-password' },
    { path: '/my-addresses' },
    { path: '/my-orders' },
    { path: '/my-orders-return' },
    { path: '/logout' },
    { path: '*' },
  ];
  
  module.exports = routes;
  